=== api-evangelist/microsoft-office-365/json-schema/microsoft-graph-event-update-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "EventUpdateRequest",
  "type": "object",
  "properties": {
    "subject": {
      "type": "string"
    },
    "locations": {
      "type": "array"
    },
    "attendees": {
      "type": "array"
    },
    "isAllDay": {
      "type": "boolean"
    },
    "isOnlineMeeting": {
      "type": "boolean"
    },
    "onlineMeetingProvider": {
      "type": "string"
    },
    "showAs": {
      "type": "string"
    },
    "importance": {
      "type": "string"
    },
    "sensitivity": {
      "type": "string"
    },
    "categories": {
      "type": "array"
    },
    "reminderMinutesBeforeStart": {
      "type": "integer"
    }
  }
}

=== api-evangelist/microsoft-office-365/examples/microsoft-graph-event-update-request-example.json
{
  "subject": "example_value",
  "locations": [],
  "attendees": [],
  "isAllDay": true,
  "isOnlineMeeting": true,
  "onlineMeetingProvider": "example_value",
  "showAs": "example_value",
  "importance": "example_value",
  "sensitivity": "example_value",
  "categories": [],
  "reminderMinutesBeforeStart": 10
}
