=== api-evangelist/microsoft-office-365/json-schema/microsoft-graph-user-update-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "UserUpdateRequest",
  "type": "object",
  "properties": {
    "displayName": {
      "type": "string"
    },
    "givenName": {
      "type": "string"
    },
    "surname": {
      "type": "string"
    },
    "jobTitle": {
      "type": "string"
    },
    "department": {
      "type": "string"
    },
    "officeLocation": {
      "type": "string"
    },
    "mobilePhone": {
      "type": "string"
    },
    "businessPhones": {
      "type": "array"
    },
    "streetAddress": {
      "type": "string"
    },
    "city": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "postalCode": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },
    "preferredLanguage": {
      "type": "string"
    },
    "accountEnabled": {
      "type": "boolean"
    },
    "usageLocation": {
      "type": "string"
    }
  }
}

=== api-evangelist/microsoft-office-365/examples/microsoft-graph-user-update-request-example.json
{
  "displayName": "example_value",
  "givenName": "example_value",
  "surname": "example_value",
  "jobTitle": "example_value",
  "department": "example_value",
  "officeLocation": "example_value",
  "mobilePhone": "example_value",
  "businessPhones": [],
  "streetAddress": "example_value",
  "city": "example_value",
  "state": "example_value",
  "postalCode": "example_value",
  "country": "example_value",
  "preferredLanguage": "example_value",
  "accountEnabled": true,
  "usageLocation": "example_value"
}
